services:

  database:
    image: postgres:15-alpine
    container_name: postgres_database 
    restart: always
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - app_net

  redis-cache:
    image: redis:latest
    container_name: redis_cache
    restart: always
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - app_net

  app:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: restaurant_api
    ports:
      - "${APP_PORT}:8000"
    environment:
      - POSTGRES_HOST=postgres_database
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis_cache 
      - REDIS_PORT=6379
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
    depends_on:
      - database
      - redis-cache
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        sleep 20 &&
        echo 'Running migrations...' &&
        alembic -c /app/alembic.ini upgrade head &&
        echo 'Starting application...' &&
        python -m app.main
        "
        
    networks:
      - app_net
    

networks:
  app_net:
    driver: bridge