services:

  database:
    image: postgres
    container_name: postgres_database 
    restart: always
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
    ports:
      - "${POSTGRES_PORT}:5432"

  redis-cache:
    image: redis:latest
    restart: always
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    ports:
      - "${REDIS_PORT}:6379"


